#!/bin/bash
set -e

name=""

while [ $# -gt 0 ]; do
  case "$1" in
  -h | --help)
    echo "First argument is want to display account or organization name."
    echo "default, your github account name."
    echo "e.g."
    echo '$ gh page yasudanaoya'
    exit 0
    ;;
  -* | --*)
    echo "$1 is not found"
    exit 0
    ;;
  *)
    name="$1"
    ;;
  esac
  shift
done

if [ -z "$name" ]; then
  name=$(git config user.name)
fi

open https://github.com/$name
